version: 0.2

phases:
  install:
    commands:
      - yum install jq -y
  pre_build:
    commands: 
      - echo REACT_APP_CTR_API=$(cat ${CODEBUILD_SRC_DIR_CTRProcessorDeployArtifact}/CTRProcessorOutput.json | jq '.CTRApi') > $CODEBUILD_SRC_DIR/ctr-viewer/.env
      - cat $CODEBUILD_SRC_DIR/ctr-viewer/.env
      - cd $CODEBUILD_SRC_DIR/ctr-viewer
      - if [ -e /tmp/node_modules.tar ]; then tar xf /tmp/node_modules.tar; fi
      - npm install
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/ctr-viewer
      - npm run build
  post_build:
    commands:
      - echo ${CODEBUILD_SRC_DIR_CTRViewerHostingDeployArtifact}
      - aws s3 sync $CODEBUILD_SRC_DIR/ctr-viewer/build s3://$(cat ${CODEBUILD_SRC_DIR_CTRViewerHostingDeployArtifact}/CTRViewerHostingOutput.json | jq '.AsettsBucket' | sed -e s/\"//g)
      - echo "build completed on `date`"
artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR/ctr-viewer/build