version: 0.1

phases:
  install:
    commands:
      - echo "nothing to do in install"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - echo "creating cloudformation\package and uploading to artifact store"
      - aws cloudformation package --template-file ./ctr-processor/template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file ./ctr-processor/packaged.yaml
  post_build:
    commands:
      - echo "build completed on `date`"

artifacts:
  files:
    - ./ctr-processor/packaged.yaml
  discard-paths: yes